name: CI

on:
  pull_request: {}
  push:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    strategy:
      matrix:
        perl: ['5.32', '5.30', '5.28']
    name: Perl ${{ matrix.perl }}
    steps:
    - uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ matrix.perl }}

    - uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - run: go get github.com/x-motemen/gobump/cmd/gobump
    - run: go get github.com/Songmu/ghch/cmd/ghch

    - uses: actions/checkout@v2

    - name: install deps
      run: |
        cpanm Module::Build::Tiny Devel::CheckBin
        cpanm --notest --installdeps .

    - name: Test
      run: perl Build.PL && ./Build && ./Build test

